"""add leader and connection timestamps to clients

Revision ID: 0b3b7ef0ef59
Revises: 
Create Date: 2025-05-03 22:50:18.338343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3b7ef0ef59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('became_leader_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('last_connected', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('last_disconnected', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'last_disconnected')
    op.drop_column('clients', 'last_connected')
    op.drop_column('clients', 'became_leader_at')
    # ### end Alembic commands ###
